<a href="https://colab.research.google.com/github/diegovalensuela/DSA/blob/master/Exerc%C3%ADcios_Sobre_M%C3%B3dulos_Python_Para_An%C3%A1lise_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercícios Sobre Módulos Python Para Análise de Dados

#####Exercício 1

In [ ]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np

In [ ]:
array = np.arange(1000000)
%time array_result = array*2
print()
lista = list(range(1000000))
%time lista_result = list(map(lambda x: x*2, lista))

CPU times: user 4.56 ms, sys: 1.96 ms, total: 6.52 ms
Wall time: 17.1 ms

CPU times: user 242 ms, sys: 134 ms, total: 376 ms
Wall time: 400 ms


#####Exercício 2

In [ ]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
array = np.arange(10)
array[5:8] = 0
print(array)

[0 1 2 3 4 0 0 0 8 9]


#####Exercício 3

In [ ]:
# Crie um array de 3 dimensões e imprima a dimensão 1
matriz = np.ones((2,3,2))
print(matriz)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
# numero de dimensões
matriz[0]

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#####Exercício 4

In [ ]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
matriz = np.array([[1,2,3,4],[4,5,6,7],[8,9,0,1]])
print(matriz)

[[1 2 3 4]
 [4 5 6 7]
 [8 9 0 1]]


In [ ]:
# imprimindo os elementos da terceira linha
matriz[2:]

array([[8, 9, 0, 1]])

In [ ]:
# imprimindo todos elementos da primeira e segunda linha e segunda e terceira coluna
matriz[[0,1],1:3]

array([[2, 3],
       [5, 6]])

#####Exercício 5

In [ ]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
np.transpose(arr)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#####Exercício 6

In [ ]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [ ]:
resultado = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
resultado

[1.1, 2.2, 1.3, 1.4, 2.5]

#####Exercício 7

In [ ]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
A = np.arange(5, 15, 1)
np.save('A.npy', A)

In [ ]:
# carregando array em B
B = np.load('A.npy')
print(B)

[ 5  6  7  8  9 10 11 12 13 14]


#####Exercício 8

In [ ]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

#####Exercício 9

In [ ]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [ ]:
data = resp.json()
data[0]['title']

'FIX: remove dependence on matplotlib.dates.epoch2num'

In [ ]:
df = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
df

number  ... state
0    35361  ...  open
1    35360  ...  open
2    35359  ...  open
3    35357  ...  open
4    35356  ...  open
5    35355  ...  open
6    35354  ...  open
7    35353  ...  open
8    35352  ...  open
9    35351  ...  open
10   35350  ...  open
11   35349  ...  open
12   35348  ...  open
13   35347  ...  open
14   35346  ...  open
15   35345  ...  open
16   35344  ...  open
17   35342  ...  open
18   35341  ...  open
19   35340  ...  open
20   35339  ...  open
21   35338  ...  open
22   35337  ...  open
23   35335  ...  open
24   35334  ...  open
25   35333  ...  open
26   35332  ...  open
27   35331  ...  open
28   35330  ...  open
29   35326  ...  open

[30 rows x 4 columns]

#####Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3

In [ ]:
banco = sqlite3.connect('exercicio.db')
cur = banco.cursor()

In [ ]:
sql_create = 'create table cursos'\
'(id integer primary key, '\
'titulo varchar(100), '\
'categoria varchar(140))'

In [ ]:
cur.execute(sql_create)

In [ ]:
sql_insert = 'insert into cursos values (?, ?, ?)'

In [ ]:
recset = [(1000, 'Ciência de dados', 'Data Science'),
          (1001, 'Big Data Fundamentos', 'Big Data'),
          (1002, 'Python Fundamentos', 'Analise de Dados')]

In [ ]:
for rec in recset:
  cur.execute(sql_insert, rec)

In [ ]:
banco.commit()

In [ ]:
sql_select = 'select * from cursos'
cur.execute(sql_select)
dados = cur.fetchall()

In [ ]:
df = pd.DataFrame(dados)

In [ ]:
df

0                     1                 2
0  1000      Ciência de dados      Data Science
1  1001  Big Data Fundamentos          Big Data
2  1002    Python Fundamentos  Analise de Dados